"""OpenStack resource spec table (os-only fields). One row per resource; the
management layer augments these with its own routing fields separately."""
from __future__ import annotations


def nova(method):
    return lambda c, a: getattr(c.compute, method)(all_projects=a)


def plain(getter):
    return lambda c, a: getter(c)


def neutron(method):  # project-scoped, or unfiltered (admin) for all_projects
    return lambda c, a: (getattr(c.network, method)() if a
                         else getattr(c.network, method)(project_id=c.current_project_id))


def cinder(method):
    return lambda c, a: getattr(c.block_storage, method)(all_projects=a)


def octavia(method):  # project-scoped, or unfiltered (admin) for all_projects
    return lambda c, a: (getattr(c.load_balancer, method)() if a
                         else getattr(c.load_balancer, method)(project_id=c.current_project_id))


CORE_SPECS = [
    # --- compute ---
    dict(name="server", fields=["id", "name", "status"],
         os_list=nova("servers"),
         os_show=lambda c, i: c.compute.get_server(c.compute.find_server(i, ignore_missing=False).id),
         os_delete=lambda c, i: c.compute.delete_server(i, ignore_missing=False),
         os_update=lambda c, i, b: c.compute.update_server(i, **b),
         update_fields=["name", "description"]),
    dict(name="flavor", fields=["id", "name", "vcpus", "ram", "disk"],
         os_list=plain(lambda c: c.compute.flavors()),
         os_show=lambda c, i: c.compute.get_flavor(i),
         os_delete=lambda c, i: c.compute.delete_flavor(i, ignore_missing=False)),
    dict(name="keypair", fields=["name", "fingerprint", "type"],
         os_list=plain(lambda c: c.compute.keypairs()),
         os_delete=lambda c, i: c.compute.delete_keypair(i, ignore_missing=False)),
    dict(name="hypervisor",
         fields=["id", "name", "status", "state", "hypervisor_type", "hypervisor_hostname"],
         os_list=plain(lambda c: c.compute.hypervisors(details=True))),
    dict(name="availability_zone", fields=["name", "state", "zoneName", "zoneState"],
         os_list=plain(lambda c: c.compute.availability_zones())),
    dict(name="aggregate", fields=["id", "name", "availability_zone", "hosts", "metadata"],
         os_list=plain(lambda c: c.compute.aggregates()),
         os_show=lambda c, i: c.compute.get_aggregate(i),
         os_update=lambda c, i, b: c.compute.update_aggregate(i, **b),
         update_fields=["name"],
         os_delete=lambda c, i: c.compute.delete_aggregate(i, ignore_missing=False)),
    dict(name="server_group", fields=["id", "name", "policy", "policies", "members"],
         os_list=plain(lambda c: c.compute.server_groups()),
         os_show=lambda c, i: c.compute.get_server_group(i),
         os_delete=lambda c, i: c.compute.delete_server_group(i, ignore_missing=False)),

    # --- network ---
    dict(name="network", fields=["id", "name", "status"],
         os_list=neutron("networks"),
         os_show=lambda c, i: c.network.get_network(i),
         os_update=lambda c, i, b: c.network.update_network(i, **b),
         update_fields=["name", "description"],
         os_delete=lambda c, i: c.network.delete_network(i, ignore_missing=False)),
    dict(name="subnet", fields=["id", "name", "cidr", "ip_version", "network_id"],
         os_list=neutron("subnets"),
         os_show=lambda c, i: c.network.get_subnet(i),
         os_update=lambda c, i, b: c.network.update_subnet(i, **b),
         update_fields=["name", "description"],
         os_delete=lambda c, i: c.network.delete_subnet(i, ignore_missing=False)),
    dict(name="router", fields=["id", "name", "status"],
         os_list=neutron("routers"),
         os_show=lambda c, i: c.network.get_router(i),
         os_update=lambda c, i, b: c.network.update_router(i, **b),
         update_fields=["name", "description"],
         os_delete=lambda c, i: c.network.delete_router(i, ignore_missing=False)),
    dict(name="port", fields=["id", "name", "status", "mac_address", "network_id"],
         os_list=neutron("ports"),
         os_show=lambda c, i: c.network.get_port(i),
         os_update=lambda c, i, b: c.network.update_port(i, **b),
         update_fields=["name", "description"],
         os_delete=lambda c, i: c.network.delete_port(i, ignore_missing=False)),
    dict(name="security_group", fields=["id", "name", "description"],
         os_list=neutron("security_groups"),
         os_show=lambda c, i: c.network.get_security_group(i),
         os_update=lambda c, i, b: c.network.update_security_group(i, **b),
         update_fields=["name", "description"],
         os_delete=lambda c, i: c.network.delete_security_group(i, ignore_missing=False)),
    dict(name="security_group_rule",
         fields=["id", "direction", "protocol", "port_range_min", "port_range_max", "ethertype"],
         os_list=neutron("security_group_rules"),
         os_delete=lambda c, i: c.network.delete_security_group_rule(i, ignore_missing=False)),
    dict(name="floating_ip", fields=["id", "floating_ip_address", "fixed_ip_address", "status", "port_id"],
         os_list=neutron("ips"),
         os_show=lambda c, i: c.network.get_ip(i),
         os_update=lambda c, i, b: c.network.update_ip(i, **b),
         update_fields=["description", "port_id"],
         os_delete=lambda c, i: c.network.delete_ip(i, ignore_missing=False)),
    dict(name="agent", fields=["id", "agent_type", "binary", "host", "alive", "admin_state_up"],
         os_list=plain(lambda c: c.network.agents()),
         os_show=lambda c, i: c.network.get_agent(i)),
    dict(name="rbac_policy",
         fields=["id", "object_type", "object_id", "action", "target_tenant", "project_id"],
         os_list=neutron("rbac_policies"),
         os_show=lambda c, i: c.network.get_rbac_policy(i)),
    dict(name="network_ip_availability",
         fields=["network_id", "network_name", "total_ips", "used_ips", "subnet_ip_availability"],
         os_list=plain(lambda c: c.network.network_ip_availabilities()),
         os_show=lambda c, i: c.network.get_network_ip_availability(i)),

    # --- storage ---
    dict(name="volume", fields=["id", "name", "status", "size"],
         os_list=cinder("volumes"),
         os_show=lambda c, i: c.block_storage.get_volume(i),
         os_delete=lambda c, i: c.block_storage.delete_volume(i, ignore_missing=False),
         os_update=lambda c, i, b: c.block_storage.update_volume(i, **b),
         update_fields=["name", "description"]),
    dict(name="volume_snapshot", fields=["id", "name", "status", "size", "volume_id"],
         os_list=cinder("snapshots"),
         os_show=lambda c, i: c.block_storage.get_snapshot(i),
         os_delete=lambda c, i: c.block_storage.delete_snapshot(i, ignore_missing=False)),
    dict(name="volume_type", fields=["id", "name", "is_public"],
         os_list=plain(lambda c: c.block_storage.types())),
    dict(name="volume_backup", fields=["id", "name", "status", "size"],
         os_list=cinder("backups"),
         os_show=lambda c, i: c.block_storage.get_backup(i),
         os_delete=lambda c, i: c.block_storage.delete_backup(i, ignore_missing=False)),
    dict(name="volume_group", fields=["id", "name", "status", "group_type", "availability_zone"],
         os_list=cinder("groups"),
         os_show=lambda c, i: c.block_storage.get_group(i)),
    dict(name="volume_group_type", fields=["id", "name", "description", "is_public", "group_specs"],
         os_list=plain(lambda c: c.block_storage.group_types()),
         os_show=lambda c, i: c.block_storage.get_group_type(i)),
    dict(name="volume_group_snapshot", fields=["id", "name", "status", "group_id", "group_type_id"],
         os_list=cinder("group_snapshots"),
         os_show=lambda c, i: c.block_storage.get_group_snapshot(i)),
    dict(name="volume_service", fields=["binary", "host", "state", "status", "zone", "updated_at"],
         os_list=plain(lambda c: c.block_storage.services())),

    # --- lbaas ---
    dict(name="load_balancer", fields=["id", "name", "provisioning_status", "operating_status", "vip_address"],
         os_list=octavia("load_balancers"),
         os_show=lambda c, i: c.load_balancer.get_load_balancer(i),
         os_delete=lambda c, i: c.load_balancer.delete_load_balancer(i, ignore_missing=False),
         os_update=lambda c, i, b: c.load_balancer.update_load_balancer(i, **b),
         update_fields=["name", "description"]),
    dict(name="listener", fields=["id", "name", "protocol", "protocol_port"],
         os_list=octavia("listeners"),
         os_show=lambda c, i: c.load_balancer.get_listener(i),
         os_delete=lambda c, i: c.load_balancer.delete_listener(i, ignore_missing=False),
         os_update=lambda c, i, b: c.load_balancer.update_listener(i, **b),
         update_fields=["name", "description"]),
    dict(name="pool", fields=["id", "name", "protocol", "lb_algorithm"],
         os_list=octavia("pools"),
         os_show=lambda c, i: c.load_balancer.get_pool(i),
         os_delete=lambda c, i: c.load_balancer.delete_pool(i, ignore_missing=False),
         os_update=lambda c, i, b: c.load_balancer.update_pool(i, **b),
         update_fields=["name", "description"]),
    dict(name="health_monitor", fields=["id", "name", "type", "delay", "timeout", "max_retries", "operating_status"],
         os_list=octavia("health_monitors"),
         os_show=lambda c, i: c.load_balancer.get_health_monitor(i),
         os_delete=lambda c, i: c.load_balancer.delete_health_monitor(i, ignore_missing=False),
         os_update=lambda c, i, b: c.load_balancer.update_health_monitor(i, **b),
         update_fields=["name"]),
    dict(name="l7_policy", fields=["id", "name", "action", "listener_id", "position", "provisioning_status"],
         os_list=octavia("l7_policies"),
         os_show=lambda c, i: c.load_balancer.get_l7_policy(i),
         os_delete=lambda c, i: c.load_balancer.delete_l7_policy(i, ignore_missing=False)),
    dict(name="lb_flavor", fields=["id", "name", "description", "flavor_profile_id", "enabled"],
         os_list=plain(lambda c: c.load_balancer.flavors()),
         os_show=lambda c, i: c.load_balancer.get_flavor(i)),

    # --- image ---
    dict(name="image", fields=["id", "name", "status", "disk_format", "visibility", "size"],
         os_list=lambda c, a: (c.image.images() if a else c.image.images(owner=c.current_project_id)),
         os_show=lambda c, i: c.image.get_image(i),
         os_delete=lambda c, i: c.image.delete_image(i, ignore_missing=False)),
    dict(name="metadef_namespace",
         fields=["namespace", "display_name", "description", "visibility", "protected", "owner"],
         os_list=plain(lambda c: c.image.metadef_namespaces()),
         os_show=lambda c, i: c.image.get_metadef_namespace(i)),

    # --- identity ---
    dict(name="project", fields=["id", "name", "description"],
         os_list=plain(lambda c: c.identity.projects()),
         os_show=lambda c, i: c.identity.get_project(i),
         os_delete=lambda c, i: c.identity.delete_project(i, ignore_missing=False)),
    dict(name="domain", fields=["id", "name", "description"],
         os_list=plain(lambda c: c.identity.domains()),
         os_show=lambda c, i: c.identity.get_domain(i),
         os_delete=lambda c, i: c.identity.delete_domain(i, ignore_missing=False)),
    dict(name="role", fields=["id", "name", "code", "alias", "domainId", "enabled"],
         os_list=plain(lambda c: c.identity.roles()),
         os_delete=lambda c, i: c.identity.delete_role(i, ignore_missing=False)),
    dict(name="user", fields=["userId", "domainId", "state", "alias", "email", "organization",
                              "id", "name", "enabled", "default_project_id"],
         os_list=plain(lambda c: c.identity.users()),
         os_show=lambda c, i: c.identity.get_user(i),
         os_delete=lambda c, i: c.identity.delete_user(i, ignore_missing=False),
         os_update=lambda c, i, b: c.identity.update_user(i, **b),
         update_fields=["name", "email"]),
    dict(name="role_assignment",
         fields=["userId", "roleCode", "alias", "projectId", "domainId"],
         os_list=plain(lambda c: c.identity.role_assignments())),
    dict(name="application_credential",
         fields=["id", "name", "description", "expires_at"],
         os_list=plain(lambda c: c.identity.application_credentials(c.current_user_id))),
    dict(name="region", fields=["id", "description", "parent_region_id"],
         os_list=plain(lambda c: c.identity.regions()),
         os_show=lambda c, i: c.identity.get_region(i)),
    dict(name="service", fields=["id", "name", "type", "description", "enabled"],
         os_list=plain(lambda c: c.identity.services()),
         os_show=lambda c, i: c.identity.get_service(i)),
    dict(name="endpoint",
         fields=["id", "service_id", "interface", "region", "url", "enabled"],
         os_list=plain(lambda c: c.identity.endpoints()),
         os_show=lambda c, i: c.identity.get_endpoint(i)),
]

RESOURCE_DOMAIN = {
    "server": "compute", "flavor": "compute", "keypair": "compute",
    "hypervisor": "compute", "availability_zone": "compute",
    "aggregate": "compute", "server_group": "compute",
    "network": "network", "subnet": "network", "router": "network",
    "port": "network", "security_group": "network",
    "security_group_rule": "network", "floating_ip": "network",
    "agent": "network", "rbac_policy": "network",
    "network_ip_availability": "network",
    "volume": "storage", "volume_snapshot": "storage", "volume_type": "storage",
    "volume_backup": "storage", "volume_group": "storage",
    "volume_group_type": "storage", "volume_group_snapshot": "storage",
    "volume_service": "storage",
    "load_balancer": "lbaas", "listener": "lbaas", "pool": "lbaas",
    "health_monitor": "lbaas", "l7_policy": "lbaas", "lb_flavor": "lbaas",
    "image": "image", "metadef_namespace": "image",
    "project": "identity", "domain": "identity", "role": "identity",
    "user": "identity", "role_assignment": "identity",
    "application_credential": "identity", "region": "identity",
    "service": "identity", "endpoint": "identity",
}
